# Generated by Django 5.0.4 on 2024-04-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizMultiAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('choiceA', models.CharField(max_length=100)),
                ('choiceB', models.CharField(max_length=100)),
                ('choiceC', models.CharField(blank=True, max_length=100, null=True)),
                ('choiceD', models.CharField(blank=True, max_length=100, null=True)),
                ('correct1', models.CharField(max_length=100)),
                ('correct2', models.CharField(max_length=100)),
                ('correct3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSingleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('choiceA', models.CharField(max_length=100)),
                ('choiceB', models.CharField(max_length=100)),
                ('choiceC', models.CharField(blank=True, max_length=100, null=True)),
                ('choiceD', models.CharField(blank=True, max_length=100, null=True)),
                ('correct', models.CharField(max_length=100)),
            ],
        ),
    ]
