# Generated by Django 5.0.4 on 2024-04-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizselectwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=10)),
                ('length', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
