# Generated by Django 5.0.4 on 2024-04-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_completedquizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizselectwords',
            name='choice5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizselectwords',
            name='choice6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizselectwords',
            name='choice7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizselectwords',
            name='choice8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
